spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/overseaproject?useSSL=false&characterEncoding=utf8&amp;
  redisson:
    address: 127.0.0.1:6379
    timeout: 3000
    database: 7 #redis有16个db 0-15
    pool: #redis连接池配置（运行前打开redis cmd redis文件夹下 minglianghang:redis-server.exe redis.windows.conf）
      max-active: 20
      max-idle: 10
      max-wait: 3000
      min-idle: 4
    #redis配置等下发
  redis:
    database: 8
    host: 127.0.0.1
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s

  # web: 静态资源存储配置（一些图片，上传之后的存放）
    #  resources:
    #     static-locations: file:E:\spring

  mvc:
    static-path-pattern: /wx/storage/fetch/**
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

server:
  port: 8080

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

logging:
  level:
    com.cug: debug
    org.apache.shiro: debug
#    com.cug: warn

mybatis:
  type-handlers-package: com.cug.cs.overseaprojectinformationsystem.typehandler
  configuration:
    map-underscore-to-camel-case: true
custom:
  jwt:
    tokenHeader: token
    expire_time: 1800000
    secret: "oversea"
#  logging.level.org.apache.shiro=DEBUG
#  logging.level.com.cug.cs=TRACE